// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktftnfrayrhcvelfcsut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZnRuZnJheXJoY3ZlbGZjc3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njg5NDcsImV4cCI6MjA2NTA0NDk0N30.0LKurPyyRD8caSTcBzK0rRQ9hcs-LvSclXTNXBI-aag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);